### ISSUE TITLE
bundle location

### ISSUE THREAD

**Issue by ghost** [benatespina/ddd-symfony#3]
This is a question. Really nice repository for DDD, well organized ideas !
The only thing that let me know is the Bundle location, while though have you put it into Infrastructure?

**Comment by benatespina** [comment]
Hi! Thanks for your feedback. Honestly I'm not maintaining this repository because collides with many concepts of DDD that I've learned after creation this repo. Perhaps, I could relaunch this repo. ;)

I put the bundle inside Infrastructure because Symfony itself is a framework and your DDD based application must be a framework agnostic app. In the moment that your domain needs something more than programming language API or your domain API (I mean about frameworks, libraries...) your app becomes opinated and you need to decouple from that.

I have some projects around this idea, check it out. Doubts, PRs or whatever you want are welcome! ;)

https://github.com/kreta/kreta
https://github.com/BenGorUser
